server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:8001/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/products/ {
        proxy_pass http://product-service:8002/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/orders/ {
        proxy_pass http://order-service:8003/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/users/ {
        proxy_pass http://user-service:8004/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/chat/ {
        proxy_pass http://chat-service:8005/;
        add_header Access-Control-Allow-Origin *;
    }
}
