server {
    listen 80;
    server_name localhost;

    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        set $upstream http://auth-service:8001;
        proxy_pass $upstream/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/products/ {
        set $upstream http://product-service:8002;
        proxy_pass $upstream/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/orders/ {
        set $upstream http://order-service:8003;
        proxy_pass $upstream/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/users/ {
        set $upstream http://user-service:8004;
        proxy_pass $upstream/;
        add_header Access-Control-Allow-Origin *;
    }

    location /api/chat/ {
        set $upstream http://chat-service:8005;
        proxy_pass $upstream/;
        add_header Access-Control-Allow-Origin *;
    }
}
